### ISSUE TITLE
postresql 로컬용 도커파일 세팅

### ISSUE THREAD

**Issue by hea9549** [TEAMOTTDEVELOPERS/cocoman_server#2]
각자 로컬에서 개발진행할때 
똑같이 postgresql 로 진행하려는데, 각자 databse, 유저명, 비밀번호 셋팅다르고하면 .. 귀찮으니까

`application-local.yaml` 보면 아래처럼 세팅해줬는데

``` yaml
url: jdbc:postgresql://localhost:5432/cocoman
    username: cocomanlocal
    password: cocomanpw
```

도커 공부겸 해볼사람이 postrgesql 이미지에 database 이름 cocoman, 유저이름 cocomanlocal, 비밀번호 cocomanpw 로 설정되어있는 도커 이미지파일 하나 만들어주면 좋을 것 같아요.

그러면 나머지 개발하는사람들은 자기컴퓨터에 postgresql 세팅할필요없이 저 도커만 띄우면

우리 서버랑 잘 작동하는 그런..!

관련질문은 슬랙이나 여기에 남겨주세요
